#!/bin/sh

# abort on errors
set -e

# build
npm run build

# navigate into the build output directory
cd dist

# if you are deploying to a custom domain
echo 'alexmassenzio.com' > CNAME

cd ../
git subtree push --prefix dist origin gh-pages