<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Users\Alex\Downloads\water_wave_for_ar\scene.gltf --transform --types
Author: Zinaida.Kovrova (https://sketchfab.com/Zinaida.Kovrova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/water-wave-for-ar-ed1507642e7e488fa0ae55528c2c1be6
Title: water_wave for AR
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useGltfAnimations, useDraco } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	ref = new Group();

	type ActionName = 'Object_0';
	type GLTFResult = {
		nodes: {
			mesh_0: THREE.Mesh;
		};
		materials: {
			PlaneShape: THREE.MeshPhysicalMaterial;
		};
	};

	const dracoLoader = useDraco();
	const gltf = useGltf<GLTFResult>('/models/water-transformed.glb', { dracoLoader });

	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	$effect(() => {
		$actions?.Object_0?.play();
	});
</script>

<T is={ref} dispose={false} {...props} rotation={[0, 0, 0]} position={[0, 61, -80]}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Sketchfab_Scene">
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<T.Group name="root">
					<T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
						<T.Group name="Sketchfab_model_7" rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.49, 1]}>
							<T.Group name="f814d653bbee4d4dbc628e0d057694efabccleanermaterialmergergle_6">
								<T.Group name="Object_2_5" rotation={[Math.PI / 2, 0, 0]}>
									<T.Group name="Object_3_4">
										<T.Group
											name="Object_13_3"
											position={[365.29, -70.73, -213.01]}
											rotation={[0, 0.15, 0]}
										>
											<T.Group name="Object_14_2">
												<T.Group name="MorphMainGroup_1">
													<T.Group name="PlaneShape_0">
														<T.Mesh
															name="mesh_0"
															geometry={gltf.nodes.mesh_0.geometry}
															material={gltf.materials.PlaneShape}
															morphTargetDictionary={gltf.nodes.mesh_0.morphTargetDictionary}
															morphTargetInfluences={gltf.nodes.mesh_0.morphTargetInfluences}
														/>
													</T.Group>
												</T.Group>
											</T.Group>
										</T.Group>
									</T.Group>
								</T.Group>
							</T.Group>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
